# Generated by Django 5.2.9 on 2025-12-17 17:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groom_name', models.CharField(max_length=200, verbose_name='Nama Mempelai Pria')),
                ('bride_name', models.CharField(max_length=200, verbose_name='Nama Mempelai Wanita')),
                ('parents_text', models.TextField(help_text='Contoh: Putra dari Bapak... dan Ibu...', verbose_name='Nama Orang Tua (Custom Text)')),
                ('instagram_username', models.CharField(blank=True, max_length=100, verbose_name='Username Instagram')),
                ('akad_date', models.DateField(verbose_name='Tanggal Akad')),
                ('akad_time', models.TimeField(verbose_name='Waktu Akad')),
                ('akad_location', models.CharField(max_length=500, verbose_name='Lokasi Akad')),
                ('akad_maps_link', models.URLField(blank=True, verbose_name='Google Maps Link Akad')),
                ('resepsi_date', models.DateField(verbose_name='Tanggal Resepsi')),
                ('resepsi_time', models.TimeField(verbose_name='Waktu Resepsi')),
                ('resepsi_location', models.CharField(max_length=500, verbose_name='Lokasi Resepsi')),
                ('resepsi_maps_link', models.URLField(blank=True, verbose_name='Google Maps Link Resepsi')),
                ('our_story', models.TextField(blank=True, verbose_name='Our Story')),
                ('save_the_date_image', models.ImageField(blank=True, upload_to='save_the_date/', verbose_name='Save the Date Image')),
                ('gift_account_number', models.CharField(blank=True, max_length=50, verbose_name='Nomor Rekening')),
                ('gift_account_name', models.CharField(blank=True, max_length=200, verbose_name='Nama Pemilik Rekening')),
                ('gift_bank_name', models.CharField(blank=True, max_length=100, verbose_name='Nama Bank')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes/', verbose_name='QR Code Check-in')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invitation',
                'verbose_name_plural': 'Invitations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nama Tamu')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='No. Telepon')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='invitations.invitation')),
            ],
            options={
                'verbose_name': 'Guest',
                'verbose_name_plural': 'Guests',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Foto')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Caption')),
                ('order', models.IntegerField(default=0, verbose_name='Urutan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='invitations.invitation')),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Galleries',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=200, verbose_name='Nama Tamu')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='No. Telepon')),
                ('status', models.CharField(choices=[('attending', 'Akan Hadir'), ('not_attending', 'Tidak Bisa Hadir'), ('maybe', 'Mungkin Hadir')], default='attending', max_length=20, verbose_name='Status Kehadiran')),
                ('message', models.TextField(blank=True, verbose_name='Pesan/Ucapan')),
                ('number_of_guests', models.IntegerField(default=1, verbose_name='Jumlah Tamu')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='invitations.invitation')),
            ],
            options={
                'verbose_name': 'RSVP',
                'verbose_name_plural': 'RSVPs',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
