# Generated by Django 5.2.9 on 2025-12-17 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nama Template')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('html_file', models.FileField(upload_to='templates/html/', verbose_name='File HTML Template')),
                ('css_file', models.FileField(blank=True, null=True, upload_to='templates/css/', verbose_name='File CSS')),
                ('js_file', models.FileField(blank=True, null=True, upload_to='templates/js/', verbose_name='File JavaScript')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='templates/previews/', verbose_name='Preview Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('is_default', models.BooleanField(default=False, verbose_name='Template Default')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invitation Template',
                'verbose_name_plural': 'Invitation Templates',
                'ordering': ['-is_default', 'name'],
            },
        ),
    ]
