# Generated by Django 5.2.8 on 2025-12-17 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation_templates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitationtemplate',
            name='css_file',
        ),
        migrations.RemoveField(
            model_name='invitationtemplate',
            name='js_file',
        ),
        migrations.CreateModel(
            name='TemplateCSS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('css_file', models.FileField(upload_to='templates/css/', verbose_name='File CSS')),
                ('order', models.IntegerField(default=0, verbose_name='Urutan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='css_files', to='invitation_templates.invitationtemplate')),
            ],
            options={
                'verbose_name': 'Template CSS',
                'verbose_name_plural': 'Template CSS Files',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='templates/images/', verbose_name='Image')),
                ('order', models.IntegerField(default=0, verbose_name='Urutan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='invitation_templates.invitationtemplate')),
            ],
            options={
                'verbose_name': 'Template Image',
                'verbose_name_plural': 'Template Images',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateJS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('js_file', models.FileField(upload_to='templates/js/', verbose_name='File JavaScript')),
                ('order', models.IntegerField(default=0, verbose_name='Urutan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='js_files', to='invitation_templates.invitationtemplate')),
            ],
            options={
                'verbose_name': 'Template JS',
                'verbose_name_plural': 'Template JS Files',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
