# Generated by Django 5.2.8 on 2025-12-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation_templates', '0002_remove_invitationtemplate_css_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitationtemplate',
            name='html_file',
        ),
        migrations.RemoveField(
            model_name='templatecss',
            name='css_file',
        ),
        migrations.RemoveField(
            model_name='templatejs',
            name='js_file',
        ),
        migrations.AddField(
            model_name='invitationtemplate',
            name='html_filename',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='File HTML Template'),
        ),
        migrations.AddField(
            model_name='templatecss',
            name='filename',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nama File CSS'),
        ),
        migrations.AddField(
            model_name='templatejs',
            name='filename',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nama File JS'),
        ),
    ]
